### ISSUE TITLE
Remove white space on error message screen

### ISSUE THREAD

**Issue by rkzack** [ournews/extensions#30]
Hi @webcolor-in could you please remove the large whitespace box at the bottom of the "Data on this publisher is not available" message screen (see attached)

<img width="388" alt="2019-10-17_0943" src="https://user-images.githubusercontent.com/35204816/67014346-b4412280-f0c2-11e9-9b90-247459334578.png">

**Comment by webcolor-in** [comment]
After we started facing height issue I have made fixed height of extension based on screen so what we can do instead of removing white is fill with sea blue color that we have. Or you propose something else?

**Comment by rkzack** [comment]
How about 1) if displaying error message above then 2) change the height of the extension.

**Comment by webcolor-in** [comment]
The height will change after add article, there are multiple such scenarios like login.

**Comment by rkzack** [comment]
OK, I don't see how that's relevant or affects my suggestion?

**Comment by rkzack** [comment]
It's ok for the height to change as is needed, unless I am missing something?

**Comment by webcolor-in** [comment]
As now it goes with fixed height, moving it to view based means calculate height again and again than just checking at start. Certainly its doable but this will simply put 2 hour estimate as height needs to be adjusted when: no article added, after article added, login view when no article added etc. If you are fine I will do it otherwise easy way is to simply make that background height to full height.

**Comment by rkzack** [comment]
2 hours to fix this properly is fine. Otherwise it doesn't look good. Please proceed.

**Comment by webcolor-in** [comment]
Fixed and code pushed

**Comment by rkzack** [comment]
This looks better, thank you. Closing issue.
